// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnZPlwXiOQwmzyQV-PbnIFN9jzG8d7ZM',
    appId: '1:134649057031:web:0b57b30251a82f471affa2',
    messagingSenderId: '134649057031',
    projectId: 'gruasrd-ce2ae',
    databaseURL: 'https://gruasrd-ce2ae-default-rtdb.firebaseio.com',
    authDomain: 'gruasrd-ce2ae.firebaseapp.com',
    storageBucket: 'gruasrd-ce2ae.firebasestorage.app',
    measurementId: 'G-K1W5T264RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhool68mqF-XYyWF_a9BTnmMVramlTLU',
    appId: '1:134649057031:android:c378ad17253652ee1affa2',
    messagingSenderId: '134649057031',
    projectId: 'gruasrd-ce2ae',
    databaseURL: 'https://gruasrd-ce2ae-default-rtdb.firebaseio.com',
    storageBucket: 'gruasrd-ce2ae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6Hw78cHjWARv7RKN1qjJsnHL9qyOM_4',
    appId: '1:134649057031:ios:204b54614e3132d61affa2',
    messagingSenderId: '134649057031',
    projectId: 'gruasrd-ce2ae',
    databaseURL: 'https://gruasrd-ce2ae-default-rtdb.firebaseio.com',
    storageBucket: 'gruasrd-ce2ae.firebasestorage.app',
    iosBundleId: 'com.gruasrd.driverApp',
  );
}
